"""Verify that ADD_LONG / ADD_SHORT are never generated by the strategy.

With the risk-first no-add refactor:
- maybe_open_or_add_long returns None when a LONG position is already held
- maybe_open_or_add_short returns None when a SHORT position is already held
- open_position blocks ADD_LONG / ADD_SHORT entirely
- extreme retest does NOT trigger ADD
- three-stage / middle-runner state does NOT allow ADD
- env MAX_LAYERS does NOT affect position sizing
- risk-based sizing uses stop_price to derive position qty
"""

from __future__ import annotations

import unittest

from src.indicators.cvd_tracker import CvdSnapshot
from src.monitors.boll_band_breakout_monitor import BollSnapshot
from src.risk.simple_position_sizer import PositionSize, SimplePositionSizer, SimplePositionSizerConfig
from src.strategies.boll_cvd_reclaim_strategy import (
    BollCvdReclaimStrategy,
    BollCvdReclaimStrategyConfig,
    StrategyPositionState,
)
from src.strategies.entry_add_flow_coordinator import EntryAddFlowCoordinator


# ── helpers ──────────────────────────────────────────────────────────────


def _sizer() -> SimplePositionSizer:
    return SimplePositionSizer(SimplePositionSizerConfig())


def _boll(
    middle: float = 2000.0,
    upper: float = 2150.0,
    lower: float = 1900.0,
    candle_ts_ms: int = 1000,
) -> BollSnapshot:
    return BollSnapshot(
        inst_id="ETH-USDT-SWAP",
        candle_ts_ms=candle_ts_ms,
        close=middle,
        middle=middle,
        upper=upper,
        lower=lower,
        upper_distance_pct=0.05,
        lower_distance_pct=0.05,
        alert_switch_on=True,
        live_mode=True,
    )


def _cvd(buy_ratio: float = 0.6, sell_ratio: float = 0.4) -> CvdSnapshot:
    return CvdSnapshot(
        ts_ms=1000,
        price=2000.0,
        side="buy",
        size=1.0,
        signed_delta=0.1,
        total_cvd=0.5,
        fast_cvd=0.1,
        previous_fast_cvd=0.09,
        buy_volume=60.0,
        sell_volume=40.0,
        buy_ratio=buy_ratio,
        sell_ratio=sell_ratio,
        cross_positive=True,
        cross_negative=False,
        cvd_increasing=True,
        cvd_decreasing=False,
        no_new_low=True,
        no_new_high=False,
        window_low=1990.0,
        window_high=2010.0,
        burst_net_move_pct=0.0,
        burst_range_pct=0.01,
        baseline_range_pct=0.001,
        burst_move_ratio=10.0,
        burst_volume=10.0,
        baseline_volume=1.0,
        burst_volume_ratio=10.0,
        up_burst=False,
        down_burst=False,
    )


def _coordinator(strategy: BollCvdReclaimStrategy) -> EntryAddFlowCoordinator:
    return EntryAddFlowCoordinator(strategy)


def _strategy(**overrides) -> BollCvdReclaimStrategy:
    config = BollCvdReclaimStrategyConfig(**overrides)
    return BollCvdReclaimStrategy(config, _sizer())


# ── tests ────────────────────────────────────────────────────────────────


class TestNoAddRiskFirst(unittest.TestCase):
    """Verify ADD is never generated under risk-first no-add runtime."""

    # ── long position blocks ADD_LONG ───────────────────────────────────

    def test_existing_long_position_blocks_add_long(self) -> None:
        """maybe_open_or_add_long returns None when side is already LONG."""
        strategy = _strategy()
        strategy.state = StrategyPositionState(
            side="LONG",
            layers=1,
            total_entry_qty=1.0,
            total_entry_notional=100.0,
            avg_entry_price=2000.0,
            tp_price=2150.0,
        )
        boll = _boll(middle=2000.0, upper=2150.0, lower=1900.0)
        cvd = _cvd(buy_ratio=0.7, sell_ratio=0.3)

        result = strategy._maybe_open_or_add_long(1995.0, 2000, boll, cvd)

        self.assertIsNone(result)
        self.assertEqual(strategy.state.layers, 1)

    def test_existing_short_position_blocks_add_short(self) -> None:
        """maybe_open_or_add_short returns None when side is already SHORT."""
        strategy = _strategy()
        strategy.state = StrategyPositionState(
            side="SHORT",
            layers=1,
            total_entry_qty=1.0,
            total_entry_notional=100.0,
            avg_entry_price=2000.0,
            tp_price=1900.0,
        )
        boll = _boll(middle=2000.0, upper=2150.0, lower=1900.0)
        cvd = _cvd(buy_ratio=0.3, sell_ratio=0.7)

        result = strategy._maybe_open_or_add_short(2005.0, 2000, boll, cvd)

        self.assertIsNone(result)
        self.assertEqual(strategy.state.layers, 1)

    # ── open_position blocks ADD_LONG / ADD_SHORT ───────────────────────

    def test_open_position_rejects_add_long(self) -> None:
        """open_position returns None for ADD_LONG intent_type."""
        strategy = _strategy()
        coord = _coordinator(strategy)
        boll = _boll()
        cvd = _cvd()

        result = coord.open_position("LONG", "ADD_LONG", 1995.0, 2000, boll, cvd, "test")

        self.assertIsNone(result)

    def test_open_position_rejects_add_short(self) -> None:
        """open_position returns None for ADD_SHORT intent_type."""
        strategy = _strategy()
        coord = _coordinator(strategy)
        boll = _boll()
        cvd = _cvd()

        result = coord.open_position("SHORT", "ADD_SHORT", 2005.0, 2000, boll, cvd, "test")

        self.assertIsNone(result)

    # ── three-stage runner does not allow ADD ────────────────────────────

    def test_three_stage_blocks_add_long(self) -> None:
        """When three_stage_runner is active, maybe_open_or_add_long returns None for ADD."""
        strategy = _strategy(three_stage_runner_enabled=True)
        strategy.state = StrategyPositionState(
            side="LONG",
            layers=1,
            total_entry_qty=1.0,
            total_entry_notional=100.0,
            avg_entry_price=2000.0,
            tp_price=2150.0,
            tp_plan="THREE_STAGE_RUNNER",
            three_stage_runner_enabled_for_position=True,
            three_stage_tp1_consumed=False,
        )
        boll = _boll()
        cvd = _cvd(buy_ratio=0.7)

        result = strategy._maybe_open_or_add_long(1995.0, 3000, boll, cvd)

        self.assertIsNone(result)

    def test_middle_runner_blocks_add_short(self) -> None:
        """When middle_runner is active, maybe_open_or_add_short returns None for ADD."""
        strategy = _strategy()
        strategy.state = StrategyPositionState(
            side="SHORT",
            layers=1,
            total_entry_qty=1.0,
            total_entry_notional=100.0,
            avg_entry_price=2000.0,
            tp_price=1900.0,
            tp_plan="MIDDLE_RUNNER",
            middle_runner_enabled_for_position=True,
            middle_runner_active=True,
        )
        boll = _boll()
        cvd = _cvd(buy_ratio=0.3, sell_ratio=0.7)

        result = strategy._maybe_open_or_add_short(2005.0, 3000, boll, cvd)

        self.assertIsNone(result)

    # ── risk-based sizing uses stop_price ───────────────────────────────

    def test_risk_based_sizing_uses_stop_price(self) -> None:
        """Position size is calculated from stop_price, not from fixed layers."""
        sizer = _sizer()
        # Default risk config: max_risk_pct=0.01, leverage=20
        size = sizer.calculate(price=2000.0, layer_index=1, stop_price=1950.0)
        # stop_distance = 50; risk_pct = 50/2000 = 0.025
        # notional = max_risk * equity / risk_pct = 0.01 * 1000 / 0.025 = 400
        # contracts = notional / price * leverage = 400 / 2000 * 20 = 4
        self.assertIsNotNone(size)
        self.assertGreater(size.eth_qty, 0)
        self.assertGreater(size.notional_usdt, 0)


if __name__ == "__main__":
    unittest.main()
