from __future__ import annotations

from decimal import Decimal
from typing import Any, Protocol, runtime_checkable

from src.execution.trader import LiveTradeResult, PositionSnapshot
from src.strategies.boll_cvd_reclaim_strategy import TradeIntent


@runtime_checkable
class LiveTraderProtocol(Protocol):
    """Protocol that every live trader must satisfy.

    This is a structural interface — any object with these attributes and
    methods satisfies the protocol.  No inheritance is required.
    """

    symbol: str
    account_equity_usdt: float
    position_contracts: Decimal
    contract_multiplier: Decimal
    contract_precision: Decimal
    min_contracts: Decimal
    leverage: str | int | float

    @property
    def broker_exchange_name(self) -> str: ...

    async def start(self) -> None: ...
    async def close(self) -> None: ...
    async def initialize(self) -> None: ...

    async def fetch_position_snapshot(self) -> PositionSnapshot: ...
    async def fetch_usdt_equity(self) -> float: ...

    async def execute_intent(self, intent: TradeIntent) -> LiveTradeResult: ...

    async def fetch_broker_open_orders(self) -> tuple[Any, ...]: ...
    async def fetch_broker_algo_orders(self) -> tuple[Any, ...]: ...
    async def recover_broker_open_orders(self) -> tuple[Any, ...]: ...
    async def fetch_broker_position(self) -> Any | None: ...
    async def fetch_broker_open_order_raws(self) -> list[dict[str, Any]]: ...
    async def fetch_broker_algo_order_raws(self) -> list[dict[str, Any]]: ...
    async def recover_broker_open_order_raws(self) -> list[dict[str, Any]]: ...
